site_name: Kubernetes Documentation
nav:
  - Kubernetes: index.md
  - Minikube & Kubectl: minikube-kubectl-install.md
  - Helm: helm.md
  - Kubernetes Dashboard: kubernetes-dashboard.md
  - Kustomize: kustomize.md
theme:
  name: material
  nav_style: dark
  palette:
    scheme: slate
    primary: indigo
    accent: light blue
